POST http://localhost:4000/collaborator/registrar
Content-Type: application/json

{
   "email": "gabriel@g.com",
    "name": "Gabriel Musse",
    "cpf": "123.456.789-99",
    "phone":"(51) 99396-7939",
    "knowledges": ["dasdas", "b"]
}
