POST http://localhost:4000/collaborator/registrar
Content-Type: application/json

{
   "email": "Gabe@g.com",
    "name": "Gabe",
    "cpf": "123.456.789-12",
    "knowledge_1": "Git",
    "knowledge_2": "React",
    "knowledge_3": "Php"
}

###
GET http://localhost:4000/collaborator/63a8f947-f684-4678-a296-76f43865b825

###
PUT http://localhost:4000/collaborator/63a8f947-f684-4678-a296-76f43865b825/unvalidate